name: Build and deploy ASP.Net Core app to Azure Web App - myapp15

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore Cadd/Cadd.sln

      - name: Build
        run: dotnet build Cadd/Cadd.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Cadd/Cadd.csproj --configuration Release --output ./publish --no-restore

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_937F11F4DD8E44338F1B1E0531BF622F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_947C0A36F66C463E8C5DF9E28368B379 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3D3B51DAE1F447C5A3FAB727F102FB1F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myapp15'
          slot-name: 'Production'
          package: ./publish
